-- MySQL Script generated by MySQL Workbench
-- Sun Nov 25 21:01:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Laiterekisteri
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Laiterekisteri` ;

-- -----------------------------------------------------
-- Schema Laiterekisteri
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Laiterekisteri` DEFAULT CHARACTER SET utf8 ;
USE `Laiterekisteri` ;

-- -----------------------------------------------------
-- Table `Laiterekisteri`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laiterekisteri`.`Customer` ;

CREATE TABLE IF NOT EXISTS `Laiterekisteri`.`Customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(30) NOT NULL,
  `lastname` VARCHAR(30) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `postal` VARCHAR(8) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `join_date` DATETIME NOT NULL,
  `last_login` DATETIME NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laiterekisteri`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laiterekisteri`.`Category` ;

CREATE TABLE IF NOT EXISTS `Laiterekisteri`.`Category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laiterekisteri`.`Devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laiterekisteri`.`Devices` ;

CREATE TABLE IF NOT EXISTS `Laiterekisteri`.`Devices` (
  `device_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `manufactor` VARCHAR(30) NOT NULL,
  `model` VARCHAR(30) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `serialnumber` VARCHAR(16) NOT NULL,
  UNIQUE INDEX `device_id_UNIQUE` (`device_id` ASC) VISIBLE,
  PRIMARY KEY (`device_id`),
  INDEX `fk_Devices_Customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_Devices_Category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Devices_Customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Laiterekisteri`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Devices_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `Laiterekisteri`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laiterekisteri`.`Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laiterekisteri`.`Reservation` ;

CREATE TABLE IF NOT EXISTS `Laiterekisteri`.`Reservation` (
  `reservation_id` INT NOT NULL,
  `device_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `reservation_time` DATETIME NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `fk_Reservation_Devices1_idx` (`device_id` ASC) VISIBLE,
  INDEX `fk_Reservation_Customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Devices1`
    FOREIGN KEY (`device_id`)
    REFERENCES `Laiterekisteri`.`Devices` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Laiterekisteri`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laiterekisteri`.`Lease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laiterekisteri`.`Lease` ;

CREATE TABLE IF NOT EXISTS `Laiterekisteri`.`Lease` (
  `reservation_id` INT NOT NULL,
  `device_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `fk_Reservation_Devices1_idx` (`device_id` ASC) VISIBLE,
  INDEX `fk_Reservation_Customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Devices10`
    FOREIGN KEY (`device_id`)
    REFERENCES `Laiterekisteri`.`Devices` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Customer10`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Laiterekisteri`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
